### ISSUE TITLE
1.3. Build and Install 配置出问题

### ISSUE THREAD

**Issue by ann25** [deepflameCFD/deepflame-dev#5]
您好，我在1.3. Build and Install 上遇到了问题。pytorch已经安装好，cuda也可以使用。前面所有步骤都是跟着安装手册安装的。但是在. install.sh这一步出现了新的问题。
![2023-05-25 11-36-28屏幕截图](https://github.com/deepflameCFD/deepflame-dev/assets/129950334/bc24dbae-cbcd-47ad-add2-2e347fd29077)

**Comment by zhixchen** [comment]
Hi, thanks for opening this issue. Our repo is now maintained at https://github.com/deepmodeling/deepflame-dev/issues, and so please set up the issue there.
